import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@shime/core";
import { auditLogs, getDatabase, notifications, users } from "@shime/db";
import { and, eq } from "drizzle-orm";
import { requireStaffSession } from "@shime/web/server/auth";
const input = z.object({ userId: z.string().uuid(), type: z.enum(["passport_issued", "questionnaire_reminder", "day_before", "event_day", "preference_open", "preference_deadline", "result_available"]), text: z.string().trim().min(1).max(5_000), scheduledAt: z.coerce.date(), dedupeKey: z.string().min(8).max(160) });
export async function POST(request: Request, { params }: { params: Promise<{ eventId: string }> }) { const requestId = randomUUID(); const session = await requireStaffSession().catch(() => null); if (!session) return NextResponse.json({ code: "UNAUTHORIZED" }, { status: 401 }); try { requirePermission(session.role, "notification:write"); } catch { return NextResponse.json({ code: "FORBIDDEN" }, { status: 403 }); } const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ code: "INVALID_INPUT" }, { status: 400 }); const { eventId } = await params; if (session.eventId && session.eventId !== eventId) return NextResponse.json({ code: "NOT_FOUND" }, { status: 404 }); const db = getDatabase(); const recipient = await db.select({ id: users.id }).from(users).where(and(eq(users.id, parsed.data.userId), eq(users.tenantId, session.tenantId))).limit(1); if (!recipient[0]) return NextResponse.json({ code: "RECIPIENT_NOT_FOUND" }, { status: 404 }); const [created] = await db.transaction(async (tx) => { const rows = await tx.insert(notifications).values({ tenantId: session.tenantId, eventId, userId: parsed.data.userId, type: parsed.data.type, dedupeKey: parsed.data.dedupeKey, scheduledAt: parsed.data.scheduledAt, payload: { text: parsed.data.text } }).onConflictDoNothing().returning(); if (rows[0]) await tx.insert(auditLogs).values({ tenantId: session.tenantId, actorUserId: session.userId, eventId, action: "notification.queue", targetType: "notification", targetId: rows[0].id, requestId }); return rows; }); return created ? NextResponse.json({ data: created }, { status: 201 }) : NextResponse.json({ code: "DUPLICATE_NOTIFICATION" }, { status: 409 }); }
