packages:
  - apps/*
  - packages/*

confirmModulesPurge: false
hoist: true

overrides:
  "minimatch@3.1.5>brace-expansion": "1.1.16"
  "next>postcss": "8.5.16"
  "@esbuild-kit/core-utils>esbuild": "0.25.12"

allowBuilds:
  argon2: true
  esbuild: true
  sharp: true
  unrs-resolver: true
