"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

type DocumentType = "event_terms" | "privacy";
type LegalDocument = { id: string; documentType: DocumentType; version: string; title: string; body: string; status: "draft" | "published" | "retired"; publishedAt: string | null; createdAt: string; updatedAt: string };
const typeLabel: Record<DocumentType, string> = { event_terms: "イベント規約", privacy: "プライバシーポリシー" };
const statusLabel = { draft: "下書き", published: "公開中", retired: "過去版" } as const;

export function LegalDocumentConsole({ eventId, eventName, initial }: { eventId: string; eventName: string; initial: LegalDocument[] }) {
  const router = useRouter(); const [documents, setDocuments] = useState(initial); const [message, setMessage] = useState(""); const [busyId, setBusyId] = useState("");
  function updateDocument(id: string, patch: Partial<LegalDocument>) { setDocuments((current) => current.map((document) => document.id === id ? { ...document, ...patch } : document)); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusyId("create"); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/admin/events/${eventId}/legal-documents`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ documentType: form.get("documentType"), version: form.get("version"), title: form.get("title"), body: form.get("body") }) }); const result = await response.json(); setBusyId(""); if (!response.ok) { setMessage(`下書きを作成できません: ${result.code}`); return; } event.currentTarget.reset(); setMessage("下書きを作成しました。"); router.refresh(); }
  async function save(document: LegalDocument) { setBusyId(document.id); setMessage(""); const response = await fetch(`/api/admin/events/${eventId}/legal-documents/${document.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "update", title: document.title, body: document.body }) }); const result = await response.json(); setBusyId(""); setMessage(response.ok ? "下書きを保存しました。" : `保存できません: ${result.code}`); if (response.ok) router.refresh(); }
  async function publish(document: LegalDocument) { if (!confirm(`${typeLabel[document.documentType]} ${document.version} を公開します。公開後は編集できません。`)) return; setBusyId(document.id); setMessage(""); const response = await fetch(`/api/admin/events/${eventId}/legal-documents/${document.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "publish" }) }); const result = await response.json(); setBusyId(""); setMessage(response.ok ? "公開し、イベントの同意対象版を更新しました。" : `公開できません: ${result.code}`); if (response.ok) router.refresh(); }
  return <div className="admin-stack"><section className="panel wide"><p className="eyebrow">LEGAL DOCUMENTS</p><h1>{eventName} 規約管理</h1><p>公開すると同じ種類の旧版は過去版になり、申込みで保存する同意版も自動で更新されます。公開後の本文は編集できません。</p><form className="settings-form" onSubmit={create}><div className="settings-grid"><label>文書種類<select name="documentType"><option value="event_terms">イベント規約</option><option value="privacy">プライバシーポリシー</option></select></label><label>版番号<input name="version" required maxLength={80} placeholder="例: 2026-08-08-v1" /></label></div><label>タイトル<input name="title" required maxLength={240} /></label><label>本文<textarea name="body" required maxLength={50000} rows={14} /></label><div className="actions"><button disabled={busyId === "create"}>{busyId === "create" ? "作成中…" : "下書きを作成"}</button><a className="button-link secondary" href="/admin">管理トップへ</a></div></form>{message && <p role="status">{message}</p>}</section>{documents.map((document) => <section className="panel wide" key={document.id}><div className="actions"><h2>{typeLabel[document.documentType]} / {document.version}</h2><span className="summary"><span>{statusLabel[document.status]}</span></span></div>{document.status === "draft" ? <><label>タイトル<input value={document.title} onChange={(event) => updateDocument(document.id, { title: event.target.value })} /></label><label>本文<textarea value={document.body} rows={14} onChange={(event) => updateDocument(document.id, { body: event.target.value })} /></label><div className="actions"><button type="button" disabled={busyId === document.id} onClick={() => save(document)}>下書きを保存</button><button type="button" className="secondary" disabled={busyId === document.id} onClick={() => publish(document)}>公開する</button></div></> : <><h3>{document.title}</h3><div className="legal-body legal-preview">{document.body}</div>{document.status === "published" && <p><a href={`/legal/${eventId}/${document.documentType}?version=${encodeURIComponent(document.version)}`} target="_blank" rel="noreferrer">公開ページを確認</a></p>}</>}</section>)}</div>;
}
