import { randomUUID } from "node:crypto";
import { and, desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { auditLogs, getDatabase, notificationTemplates } from "@shime/db";
import { requireStaffSession } from "../../../../../server/auth";

const input = z.object({ templateKey: z.string().trim().regex(/^[a-z0-9_]{2,80}$/), name: z.string().trim().min(1).max(160), body: z.string().trim().min(1).max(5000) });
export async function POST(request: Request) { const requestId = randomUUID(); const session = await requireStaffSession().catch(() => null); if (!session) return NextResponse.json({ code: "UNAUTHORIZED" }, { status: 401 }); if (session.role !== "system_admin") return NextResponse.json({ code: "FORBIDDEN" }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ code: "INVALID_INPUT" }, { status: 400 }); const db = getDatabase(); const current = await db.select().from(notificationTemplates).where(and(eq(notificationTemplates.tenantId, session.tenantId), eq(notificationTemplates.templateKey, parsed.data.templateKey))).orderBy(desc(notificationTemplates.version)).limit(1); const version = (current[0]?.version ?? 0) + 1; const [created] = await db.transaction(async (tx) => { await tx.update(notificationTemplates).set({ active: false, updatedAt: new Date() }).where(and(eq(notificationTemplates.tenantId, session.tenantId), eq(notificationTemplates.templateKey, parsed.data.templateKey))); const rows = await tx.insert(notificationTemplates).values({ tenantId: session.tenantId, ...parsed.data, version, active: true, updatedBy: session.userId }).returning(); await tx.insert(auditLogs).values({ tenantId: session.tenantId, actorUserId: session.userId, action: "notification_template.version.create", targetType: "notification_template", targetId: rows[0]?.id, after: { templateKey: parsed.data.templateKey, version }, requestId }); return rows; }); return NextResponse.json({ data: created }, { status: 201 }); }
