import { randomUUID } from "node:crypto";
import { and, eq, inArray } from "drizzle-orm";
import { NextResponse } from "next/server";
import { applicationInputSchema, normalizeEmail, normalizePhone, requirePermission, shouldProvisionParticipant } from "@shime/core";
import { applicationImportRows, applicationImports, applications, auditLogs, getDatabase, participants } from "@shime/db";
import { requireStaffSession } from "../../../../../../../../server/auth";
type Context = { params: Promise<{ eventId: string; importId: string }> };
export async function POST(_request: Request, context: Context) {
  const requestId = randomUUID(); const session = await requireStaffSession().catch(() => null); if (!session) return NextResponse.json({ code: "UNAUTHORIZED" }, { status: 401 });
  try { requirePermission(session.role, "application:import"); } catch { return NextResponse.json({ code: "FORBIDDEN" }, { status: 403 }); }
  const { eventId, importId } = await context.params; const db = getDatabase(); const importRows = await db.select().from(applicationImports).where(and(eq(applicationImports.id, importId), eq(applicationImports.eventId, eventId), eq(applicationImports.tenantId, session.tenantId))).limit(1); const job = importRows[0];
  if (!job || job.status !== "validated") return NextResponse.json({ code: "IMPORT_NOT_COMMITTABLE" }, { status: 409 }); if (job.mode === "all" && job.errorRows > 0) return NextResponse.json({ code: "IMPORT_HAS_ERRORS" }, { status: 409 });
  const rows = await db.select().from(applicationImportRows).where(and(eq(applicationImportRows.importId, importId), eq(applicationImportRows.tenantId, session.tenantId), inArray(applicationImportRows.level, ["valid", "warning"]))); let committed = 0; let participantsCreated = 0;
  await db.transaction(async (tx) => { await tx.update(applicationImports).set({ status: "committing", updatedAt: new Date() }).where(eq(applicationImports.id, importId)); for (const row of rows) { const parsed = applicationInputSchema.safeParse(row.normalizedData); if (!parsed.success || !parsed.data.externalId) continue; const input = parsed.data; const [saved] = await tx.insert(applications).values({ tenantId: session.tenantId, eventId, source: "csv", externalId: input.externalId, status: input.status, fullName: input.fullName, fullNameKana: input.fullNameKana, phone: input.phone, phoneNormalized: normalizePhone(input.phone), email: input.email, emailNormalized: normalizeEmail(input.email), birthDate: input.birthDate, nickname: input.nickname, residenceArea: input.residenceArea, participantCategory: input.participantCategory, notes: input.notes, submittedAt: new Date() }).onConflictDoUpdate({ target: [applications.tenantId, applications.eventId, applications.externalId], set: { status: input.status, fullName: input.fullName, fullNameKana: input.fullNameKana, phone: input.phone, phoneNormalized: normalizePhone(input.phone), email: input.email, emailNormalized: normalizeEmail(input.email), birthDate: input.birthDate, nickname: input.nickname, residenceArea: input.residenceArea, participantCategory: input.participantCategory, notes: input.notes, updatedAt: new Date() } }).returning(); if (saved) { committed++; if (shouldProvisionParticipant(input.status)) { const created = await tx.insert(participants).values({ tenantId: session.tenantId, eventId, applicationId: saved.id, status: "confirmed" }).onConflictDoNothing({ target: [participants.tenantId, participants.eventId, participants.applicationId] }).returning({ id: participants.id }); participantsCreated += created.length; } await tx.update(applicationImportRows).set({ committedApplicationId: saved.id, updatedAt: new Date() }).where(eq(applicationImportRows.id, row.id)); } } await tx.update(applicationImports).set({ status: "completed", committedAt: new Date(), updatedAt: new Date() }).where(eq(applicationImports.id, importId)); await tx.insert(auditLogs).values({ tenantId: session.tenantId, actorUserId: session.userId, eventId, action: "application_import.commit", targetType: "application_import", targetId: importId, after: { committedRows: committed, participantsCreated }, requestId }); });
  return NextResponse.json({ data: { committedRows: committed, participantsCreated }, request_id: requestId });
}
