import { and, eq, gt } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { hashSessionToken, parseQrPayload, requirePermission } from "@shime/core";
import { applications, checkins, getDatabase, lovePassports, participants } from "@shime/db";
import { getEnv } from "@shime/web/env";
import { requireStaffSession } from "@shime/web/server/auth";
const input = z.object({ qrToken: z.string().min(32).max(207) });
export async function POST(request: Request, { params }: { params: Promise<{ eventId: string }> }) { const session = await requireStaffSession().catch(() => null); if (!session) return NextResponse.json({ code: "UNAUTHORIZED" }, { status: 401 }); try { requirePermission(session.role, "checkin:write"); } catch { return NextResponse.json({ code: "FORBIDDEN" }, { status: 403 }); } const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ code: "INVALID_QR" }, { status: 400 }); let qrToken; try { qrToken = parseQrPayload(parsed.data.qrToken); } catch { return NextResponse.json({ code: "INVALID_QR" }, { status: 400 }); } const { eventId } = await params; const db = getDatabase(); const rows = await db.select({ participantId: participants.id, participantNumber: participants.participantNumber, participantStatus: participants.status, fullName: applications.fullName, passportStatus: lovePassports.status }).from(lovePassports).innerJoin(participants, and(eq(participants.id, lovePassports.participantId), eq(participants.tenantId, lovePassports.tenantId))).innerJoin(applications, and(eq(applications.id, participants.applicationId), eq(applications.tenantId, participants.tenantId))).where(and(eq(lovePassports.tenantId, session.tenantId), eq(lovePassports.eventId, eventId), eq(lovePassports.qrTokenHash, hashSessionToken(qrToken, getEnv().QR_TOKEN_PEPPER)), gt(lovePassports.qrExpiresAt, new Date()))).limit(1); const target = rows[0]; if (!target) return NextResponse.json({ code: "INVALID_OR_EXPIRED_QR" }, { status: 404 }); const existing = await db.select({ status: checkins.status, checkedInAt: checkins.checkedInAt }).from(checkins).where(and(eq(checkins.tenantId, session.tenantId), eq(checkins.eventId, eventId), eq(checkins.participantId, target.participantId))).limit(1); return NextResponse.json({ data: { ...target, alreadyCheckedIn: existing[0]?.status === "checked_in", checkedInAt: existing[0]?.checkedInAt } }); }
